### ISSUE TITLE
Eventum 3.1.3 Setting time tracker PHP Fatal Error

### ISSUE THREAD

**Issue by dgossage** [eventum/eventum#204] opened 2016-10-03 15:34 UTC
Eventum 3.1.3 recently upgraded from 2.3.x to 2.3.6 -> 3.0.x ->3.1.3
Centos7
php 5.6 via remi repo

Trying to add time tracking to a ticket results in following:

```
[03-Oct-2016 15:06:12 UTC] app.ERROR: Uncaught Exception Exception: "DateTime::__construct(): Failed to parse time string (2016-10-03 10:20:00 US/Central) at position 20 (U): The timezone could not be found in the database" at /www/sites/www.checktix.com/public/lib/eventum/class.date_helper.php line 53 {"exception":"[object] (Exception(code: 0): DateTime::__construct(): Failed to parse time string (2016-10-03 10:20:00 US/Central) at position 20 (U): The timezone could not be found in the database at /www/sites/www.checktix.com/public/lib/eventum/class.date_helper.php:53)"} {"url":"/time_tracking.php?iss_id=88606","ip":"192.168.11.158","http_method":"POST","server":"www.checktix.com","referrer":"https://www.checktix.com/time_tracking.php?iss_id=88606","file":null,"line":null,"class":null,"function":null,"memory_usage":"6 MB","memory_peak_usage":"6 MB","version":"3.1.3","usr_id":"48"}
[03-Oct-2016 15:06:13 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (2016-10-03 10:20:00 US/Central) at position 20 (U): The timezone could not be found in the database' in /www/sites/www.checktix.com/public/lib/eventum/class.date_helper.php:53
Stack trace:
#0 /www/sites/www.checktix.com/public/lib/eventum/class.date_helper.php(53): DateTime->__construct('2016-10-03 10:2...', Object(DateTimeZone))
#1 /www/sites/www.checktix.com/public/lib/eventum/class.date_helper.php(317): Date_Helper::getDateTime('2016-10-03 10:2...')
#2 /www/sites/www.checktix.com/public/lib/eventum/class.time_tracking.php(510): Date_Helper::convertDateGMT('2016-10-03 10:2...')
#3 /www/sites/www.checktix.com/public/src/Controller/TimeTrackingController.php(108): Time_Tracking::addTimeEntry(88606, 14, 5, Array, 'test')
#4 /www/sites/www.checktix.com/public/src/Controller/TimeTrackingController.php(92): Eventum\Controller\TimeTrackingController->addTimeEntry()
#5 /www/sites/www.checktix.com/public/src/Controller in /www/sites/www.checktix.com/public/lib/eventum/class.date_helper.php on line 53

```

php.ini does have my timezone set and it shows up in php -i as set.

Looking thoruhg settings in administration I did not find offhand anywhere a timezone would be set unless I missed it.

**Comment by glensc** [comment] 2016-10-11 17:49
timezones were converted in from Long Names to Abbrevation in #53

the patch [upgrade/patches/30_migrate_tz.php](https://github.com/glensc/eventum/blob/d5df8e305e0e387ea5fc61a1e3a12335aaefbf65/upgrade/patches/30_migrate_tz.php) tried to do best, but it can not handle all situations.

if you know your timezone abbrevation you can patch database manually with:

```sql
update user_preference set upr_timezone='XXX' where upr_timezone != 'US/Central';
```

replace `XXX` with the abbreviation, like `EET` for `Europe/Tallinn`

**Comment by glensc** [comment] 2016-10-11 17:51
also, the timezone is set per user, so each user needs to visit their `Preferences` (`preferences.php`)

**Comment by glensc** [comment] 2016-10-11 17:54
err. disregard my [earlier post](https://github.com/eventum/eventum/issues/204#issuecomment-252992157) the conversion was done Abbrevation to Full Timezone Name, i.e `EET` => `Europe/Tallinn`.

so looks like your timezone is set to `US/Central` and [DateTimeZone](http://php.net/datetimezone) can not parse it?

i'll try  to reproduce this meanwhile

**Comment by dgossage** [comment] 2016-10-11 18:00
I did see that by changing my timezone in user prefs to what php.ini has set as America/Chicago did allow me to now add a time entry.

**Comment by dgossage** [comment] 2016-10-11 18:01
And yes in user prefs before it was set as US/Central when failing

**Comment by glensc** [comment] 2016-10-11 18:21
```sql
update user_preference set upr_timezone='America/Chicago' where upr_timezone='US/Central';
```

should fix your database.

**Comment by glensc** [comment] 2016-10-11 18:21
do you know how `US/Central` got to your database? it was set so in earlier version, i.e 2.3.x?

**Comment by glensc** [comment] 2016-10-11 18:27
reproduced:

```
➔ php -r 'var_dump(new DateTime("2016-10-03 10:20:00 America/Chicago"));'
Command line code:1:
class DateTime#1 (3) {
  public $date =>
  string(26) "2016-10-03 10:20:00.000000"
  public $timezone_type =>
  int(3)
  public $timezone =>
  string(15) "America/Chicago"
}

➔ php -r 'var_dump(new DateTime("2016-10-03 10:20:00 US/Central"));'
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (2016-10-03 10:20:00 US/Central) at position 20 (U): The timezone could not be found in the database' in Command line code:1
Stack trace:
#0 Command line code(1): DateTime->__construct('2016-10-03 10:2...')
#1 {main}
  thrown in Command line code on line 1
➔ 
```

**Comment by dgossage** [comment] 2016-10-11 18:31
Well my 2.3.x install was from few years back so not sure if that was default set at the time.  I didn't actively go in and change it ever to US/Central or as far back as I can recall ever run it on a system using US/Central as the timezone.  Only about 4-5 users had that set as the timezone as well.  Most were UTC or America/Chicago already.

**Comment by glensc** [comment] 2016-10-11 18:33
I was rather thinking was the data from old installation or the conversion script saved it so. If you have old database around you could check.

I'm going to close the issue. I don't see clean way to handle this.

**Closed by glensc** 2016-10-11 18:33 UTC
Labels: question
