### ISSUE TITLE
Email download error

### ISSUE THREAD

**Issue by shiyamk** [eventum/eventum#1262] opened 2021-11-16 16:49 UTC
Hi,

i have been getting the following error when i try to download mail from an imap server using cronjob. no idea how to identify the issue. anyone able to help me with this?

i have eventum setup on Ubuntu 18.03, PHP 7.3, Apache 2, MySQL.

```
[2021-11-16 16:42:07] app.ERROR: Eventum\Model\Repository\IssueRepository 0 not found

{
  "account": "outlook.office365.com[example@example.com]/Critical",
  "resource": "[object] (Eventum\\Mail\\Imap\\ImapResource: #3403 <758210504.772.1636475992539.JavaMail.monitor@abc.co.uk>)",
  "class": "Doctrine\\ORM\\EntityNotFoundException",
  "e": "[object] (Doctrine\\ORM\\EntityNotFoundException(code: 0): Eventum\\Model\\Repository\\IssueRepository 0 not found at /var/www/html/eventum/src/Model/Repository/Traits/FindByIdTrait.php:32)"
}
{
  "file": "/var/www/html/eventum/src/Logger/LoggerTrait.php",
  "line": 29,
  "class": "Eventum\\Console\\Command\\BaseCommand",
  "function": "log",
  "memory_peak_usage": "16 MB",
  "memory_usage": "16 MB"
}

16:42:07 ERROR     [app] Eventum\Model\Repository\IssueRepository 0 not found 

["account" => "outlook.office365.com[example@example.com]/Critical",
"resource" => Eventum\Mail\Imap\ImapResource^ { …},
"class" => "Doctrine\ORM\EntityNotFoundException",
"e" => Doctrine\ORM\EntityNotFoundException^ { …}] ["file" => "/var/www/html/eventum/src/Logger/LoggerTrait.php",
"line" => 29,
"class" => "Eventum\Console\Command\BaseCommand",
"function" => "log",
"memory_peak_usage" => "16 MB",
"memory_usage" => "16 MB"]
```

**Comment by glensc** [comment] 2021-11-16 16:58
Why have you omitted Eventum version from bug report?

**Comment by vladsf** [comment] 2021-11-16 19:25
I saw this issue a month ago, but I forgot how I solved that :/

**Comment by glensc** [comment] 2021-11-16 19:29
Have you tried issue search?
- https://github.com/eventum/eventum/search?q=%22IssueRepository+0+not+found%22+is%3Aissue&type=issues

**Comment by vladsf** [comment] 2021-11-17 06:52
> Have you tried issue search?
> 
>     * https://github.com/eventum/eventum/search?q=%22IssueRepository+0+not+found%22+is%3Aissue&type=issues

Yes, exactly. Thanks! :+1:

**Comment by glensc** [comment] 2021-11-17 09:13
@vladsf so, point it out then which one, and even better extract the answer as well.

**Comment by vladsf** [comment] 2021-11-17 09:38
@glensc this one #1182

**Comment by glensc** [comment] 2021-11-17 09:43
Thankx @vladsf,

Since it's still open, closing as duplicate of https://github.com/eventum/eventum/issues/1182

**Closed by glensc** 2021-11-17 09:43 UTC

**Comment by shiyamk** [comment] 2021-11-17 12:29
Sorry I am using  eventum-3.10.8. i followed some of the solutions/workarounds suggested on #578 and it worked. now I can see the issues created but at the same time I see the following error.

`[2021-11-17 12:15:39] app.ERROR: Header MUST contain a field name {"account":"outlook.office365.com[example@example.com]/Critical","resource":"[object] (Eventum\\Mail\\Imap\\ImapResource: #3635 <xxx-xxx-xxxxxx.amazonses.com>)","class":"Laminas\\Mail\\Header\\Exception\\InvalidArgumentException","e":"[object] (Laminas\\Mail\\Header\\Exception\\InvalidArgumentException(code: 0): Header MUST contain a field name at /var/www/html/eventum/vendor/laminas/laminas-mail/src/Header/GenericHeader.php:76)"} {"file":"/var/www/html/eventum/src/Logger/LoggerTrait.php","line":29,"class":"Eventum\\Console\\Command\\BaseCommand","function":"log","memory_peak_usage":"22 MB","memory_usage":"22 MB"}
12:15:39 ERROR     [app] Header MUST contain a field name ["account" => "outlook.office365.com[example@example.com]/Critical","resource" => Eventum\Mail\Imap\ImapResource^ { …},"class" => "Laminas\Mail\Header\Exception\InvalidArgumentException","e" => Laminas\Mail\Header\Exception\InvalidArgumentException^ { …}] ["file" => "/var/www/html/eventum/src/Logger/LoggerTrait.php","line" => 29,"class" => "Eventum\Console\Command\BaseCommand","function" => "log","memory_peak_usage" => "22 MB","memory_usage" => "22 MB"]`

should i do any further changes or can i ignore this at this stage?

**Comment by glensc** [comment] 2021-11-17 13:17
the same, add debug
