### ISSUE TITLE
Email issues when upgrading from 2.3.3 to 3.0.2

### ISSUE THREAD

**Issue by cmiller1111** [eventum/eventum#83] opened 2015-10-27 17:42 UTC
Hi!

I upgraded from 2.3.3 to 3.0.2 on an Ubuntu 12 machine and the email notifications are no longer working.  Fortunately I made this upgrade on a clone so I've been able to compare the settings of the functional 2.3.3 to the non-functional 3.0.2 and am seeing no difference.  I've dug through all of the class.email....php files and am seeing no irregularities.  Is there something I need to change to fix this?

Thanks for your help!

**Comment by cpinfold** [comment] 2015-10-27 17:52
Do the notifications work if you run the script manually?  Are your cron
jobs pointing to the "bin" directory instead of "crons"?

Craig.

**Comment by cmiller1111** [comment] 2015-10-27 18:26
I'm pretty new to eventum and linux, how would I go about running the script manually?  Yes the cron jobs are pointing at bin and not cron.

**Comment by glensc** [comment] 2015-10-27 18:33
`php /path/to/the/script/to/execute.php`

but it's best to use user that cron does, otherwise it may create files as root later unaccessible for webserver. so let's assume webserver runs as `www-data`, you invoke:

```
sudo -H -u www-data php /path/to/the/script/to/execute.php
```

**Comment by cpinfold** [comment] 2015-10-27 18:38
Also are you seeing anything in /path/to/eventum/logs/errors.log ?  You can
view this with "tail -50 /path/to/eventum/logs/errors.log"

Craig.

**Comment by cmiller1111** [comment] 2015-10-27 18:42
I changed a few things to remove company information but here's the error

The error message passed to us was:

'Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]'

A more detailed error message follows:

''

A backtrace is available:

APP_INC_PATH/class.mail_queue.php:197
  Mail_Queue::_sendEmail((string )'', (string )'MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
Message-ID: <eventum.54gp77v7u.fq96n1@[localhost.domain.com]>
From: "Eventum - CFSR OMS " <[user@domain.com]>
To:
Subject: [#2184] New Issue: Test Bug - Testing New Eventum
precedence: bulk
Auto-submitted: auto-generated
Date: Thu, 22 Oct 2015 17:44:09 +0000', (string )'This is an automated message sent at your request from Eventum.

**Comment by cpinfold** [comment] 2015-10-27 19:01
It looks like the email recipient is empty (first parameter to
_sendEmail).  When you look at the issue notification list for ticket 2184
any email address under other is a proper email address? (Not blank) When
you look at the Eventum Users assigned to ticket 2184, they all have valid
and non-blank email addresses?

Craig.

**Comment by cmiller1111** [comment] 2015-10-27 19:53
Yup, the email addresses attached to that issue are full working email addresses.

**Comment by glensc** [comment] 2015-10-27 20:33
err, you should run the scripts in `bin/` dir, not classes themselves

wiki doc about cron tasks:
https://github.com/eventum/eventum/wiki/System-Admin%3A-Doing-a-fresh-install#scheduled-tasks

**Comment by cmiller1111** [comment] 2015-10-27 20:40
ok awesome, when I run $ php process_mail_queue.php brom the bin/ dir, i get this set of error messages


Mail_Queue: issue #2185: Can't send mail 46461: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]
Mail_Queue: issue #2186: Can't send mail 46465: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]
Mail_Queue: issue #2188: Can't send mail 46470: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]
Mail_Queue: issue #2172: Can't send mail 46420: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]
Mail_Queue: issue #2173: Can't send mail 46423: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]
Mail_Queue: issue #2175: Can't send mail 46428: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]
Mail_Queue: issue #2176: Can't send mail 46431: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]
Mail_Queue: issue #2177: Can't send mail 46434: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]
Mail_Queue: issue #2184: Can't send mail 46455: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]
Mail_Queue: issue #2185: Can't send mail 46461: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]
Mail_Queue: issue #2186: Can't send mail 46465: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]
Mail_Queue: issue #2188: Can't send mail 46470: Failed to add recipient: @localhost [SMTP: Invalid response code received from server (code: 501, response: <@localhost>: no local part)]

so it looks like none of the issues are able to send emails

**Comment by glensc** [comment] 2015-10-27 21:22
as seen from your [post](https://github.com/eventum/eventum/issues/83#issuecomment-151605891), the `To:` header is empty.

**Comment by cmiller1111** [comment] 2015-10-27 21:24
all of those issues were created in the 2.3.3 version and were sending notifications fine.  The issues all still have those users attached to them and the user accounts have valid emails attached to them as visible in the web app.  Is there a bug when upgrading to 3.0.2 where it is unable to pull the email information from the user?

**Comment by glensc** [comment] 2015-10-27 21:25
if  there were bug, then it would be fixed in 3.0.3 already, it is not known what the bug is

check the database and whether [Mail_Queue::add](https://github.com/eventum/eventum/blob/master/lib/eventum/class.mail_queue.php#L52) is called with invalid parmeters or not

**Comment by glensc** [comment] 2015-10-27 21:36
can you join this? https://gitter.im/eventum/eventum

**Comment by cmiller1111** [comment] 2015-10-28 17:35
mysql> select * from mail_queue order by maq_iss_id desc limit 1;
+--------+------------+---------------------+------------+---------------+-----------------------+---------------+-----------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-------------+
| maq_id | maq_iss_id | maq_queued_date     | maq_status | maq_save_copy | maq_sender_ip_address | maq_recipient | maq_subject                       | maq_headers                                                                                                                                                                                                                                                                                                                                                                     | maq_body                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | maq_type  | maq_usr_id | maq_type_id |
+--------+------------+---------------------+------------+---------------+-----------------------+---------------+-----------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-------------+
|  46470 |       2188 | 2015-10-27 19:58:17 | error      |             1 | 10.0.40.200           |               | [#2188] New Issue: New Test Issue | MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
Message-ID: <eventum.54ipz5igd.bhvge8@dmz.ubuntuhost1-clone.ourdomain.com>
From: "Eventum - CFSR OMS " <slee@ourdomain.com>
To:
Subject: [#2188] New Issue: New Test Issue
precedence: bulk
Auto-submitted: auto-generated
Date: Tue, 27 Oct 2015 19:58:17 +0000 | This is an automated message sent at your request from Eventum.

A new issue was just created in the system.

To view more details of this issue, or to update it, please visit the
following URL:
http://dmz.ubuntuhost1-clone.ourdomain.com/eventum/view.php?id=2188

----------------------------------------------------------------------
                ID: 2188
           Summary: New Test Issue
           Project: CFSR - Round 3
       Reported By: Chuck Miller
        Assignment: Chuck Miller
          Priority: Critical
       Description:
----------------------------------------------------------------------
testing the error logs
----------------------------------------------------------------------


Please Note: If you do not wish to receive any future email
notifications from Eventum, please change your account preferences by
visiting the URL below:
http://dmz.ubuntuhost1-clone.ourdomain.com/eventum/preferences.php
| new_issue |       NULL |        NULL |
+--------+------------+---------------------+------------+---------------+-----------------------+---------------+-----------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-------------+
1 row in set (0.01 sec)

**Comment by glensc** [comment] 2015-10-28 18:07
terminate commands with `\G` not `;` - more readable,
and enclose such pastes in blockquote:

    ```
    something
    ```

ps: you can edit your own posts

**Comment by cmiller1111** [comment] 2015-10-28 18:28
thanks for the tip, changes made!

**Comment by glensc** [comment] 2015-11-02 10:29
is the problem solved now?

**Comment by cmiller1111** [comment] 2015-11-04 18:36
Hi, sorry to get back so late.  This issue is not solved and I'm unable to figure out why maq_recipient is empty.  Where does that information get pulled from?

**Comment by glensc** [comment] 2015-11-04 19:07
i answered what to do next:

https://github.com/eventum/eventum/issues/83#issuecomment-151649173

**Comment by cmiller1111** [comment] 2015-11-04 19:13
right, you said check the database and sent a link to the php file.  I looked in that php file on my server and saw nothing different except that it's immensely shorter (I can post here if you'd like).  Do you want me to go into the sql db and see if it's calling Mail_Queue::add with valid parameters?  Sorry, like I said I'm a beginner here so need more basic instructions.

**Comment by cmiller1111** [comment] 2015-11-04 19:17
```
/* vim: set expandtab tabstop=4 shiftwidth=4 encoding=utf-8: */
// +----------------------------------------------------------------------+
// | Eventum - Issue Tracking System                                      |
// +----------------------------------------------------------------------+
// | Copyright (c) 2003 - 2008 MySQL AB                                   |
// | Copyright (c) 2008 - 2010 Sun Microsystem Inc.                       |
// | Copyright (c) 2011 - 2014 Eventum Team.                              |
// |                                                                      |
// | This program is free software; you can redistribute it and/or modify |
// | it under the terms of the GNU General Public License as published by |
// | the Free Software Foundation; either version 2 of the License, or    |
// | (at your option) any later version.                                  |
// |                                                                      |
// | This program is distributed in the hope that it will be useful,      |
// | but WITHOUT ANY WARRANTY; without even the implied warranty of       |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        |
// | GNU General Public License for more details.                         |
// |                                                                      |
// | You should have received a copy of the GNU General Public License    |
// | along with this program; if not, write to:                           |
// |                                                                      |
// | Free Software Foundation, Inc.                                       |
// | 51 Franklin Street, Suite 330                                          |
// | Boston, MA 02110-1301, USA.                                          |
// +----------------------------------------------------------------------+
// | Authors: JoÃ£o Prado Maia <jpm@mysql.com>                            |
// | Authors: Elan RuusamÃ¤e <glen@delfi.ee>                              |
// +----------------------------------------------------------------------+

class Mail_Queue
{
    /**
     * Adds an email to the outgoing mail queue.
     *
     * @param   string $recipient The recipient of this email
     * @param   array $headers The list of headers that should be sent with this email
     * @param   string $body The body of the message
     * @param   integer $save_email_copy Whether to send a copy of this email to a configurable address or not (ev$
     * @param   integer $issue_id The ID of the issue. If false, email will not be associated with issue.
     * @param   string $type The type of message this is.
     * @param   integer $sender_usr_id The id of the user sending this email.
     * @param   integer $type_id The ID of the event that triggered this notification (issue_id, sup_id, not_id, e$
     * @return  true, or a PEAR_Error object
     */
    public static function add($recipient, $headers, $body, $save_email_copy = 0, $issue_id = false, $type = '', $$
    {
        Workflow::modifyMailQueue(Auth::getCurrentProject(false), $recipient, $headers, $body, $issue_id, $type, $$

        // avoid sending emails out to users with inactive status
        $recipient_email = Mail_Helper::getEmailAddress($recipient);
        $usr_id = User::getUserIDByEmail($recipient_email);
        if (!empty($usr_id)) {
            $user_status = User::getStatusByEmail($recipient_email);
            // if user is not set to an active status, then silently ignore
            if ((!User::isActiveStatus($user_status)) && (!User::isPendingStatus($user_status))) {
                return false;
            }
        }

        $to_usr_id = User::getUserIDByEmail($recipient_email);
        $recipient = Mail_Helper::fixAddressQuoting($recipient);

        $reminder_addresses = Reminder::_getReminderAlertAddresses();
```

**Comment by glensc** [comment] 2015-11-04 20:18
what i said that you debug CALL to that method, the sourcecode i can look up from git any time. the problem is with your system, i.e some unknown quirk, not the sourcecode.

you need to var_dump or print_r the data, and see if that gives any ideas. it's php debugging, no eventum knowledge needed.

**Comment by poing** [comment] 2015-11-05 06:17
I suggest you take a look at the mail queue for more information:
`SELECT * FROM mail_queue  WHERE maq_status != "sent";`

Sometimes my users forgot to enter a comma between addresses.  `maq_recipient` should contain a **single** recipient address for each item in the mail queue.

Did you enable mailing system status or error messages, is the address set?  These message show up in the mail queue as `maq_iss_id = 0`.

**Comment by cpinfold** [comment] 2015-11-05 16:33
Hi Brian,

Chuck did as you suggested on a Gitter chat (
https://gitter.im/eventum/eventum) and what he's seeing is blank values in
the maq_recipient.  What we don't know is how these blank values were
inserted.  That was the debugging that Elan was referring to.

Ideally some print_r or var_dump on the $recipient in the add method of the
Mail_Queue class and if empty work back to where that was called to see how
it becomes blank.

Chuck - eg. a new first line of the add method of the Mail_Queue class:
`echo( "Recipient in add is: '" . print_r($recipient, true) . "'<BR>");`

Craig.

**Comment by cmiller1111** [comment] 2015-11-11 19:06
This issue can be closed.  The emails were being blacklisted by our exchange server; once we added an exemption for the eventum host server in exchange the emails began coming through.

**Comment by glensc** [comment] 2015-11-11 19:13
you can close your own created tickets!

**Closed** 2015-11-11 19:14 UTC
Labels: bug
