### ISSUE TITLE
Post update tickets not imported

### ISSUE THREAD

**Issue by dgossage** [eventum/eventum#496] opened 2019-03-07 21:23 UTC
Updated to 3.5.6 last evening and now for emails that get generated from a website developers made they no longer are accepted.  I may not be able to get them to look into it if issue is with how they are generating the emails right away.  They create issues from php and send them to project email.

> > In Part.php line 296:
>                                                            
>   Header with Name Content-Type or content-type not found  
>                                                            
> 
> mail:download [--limit LIMIT] [--no-lock] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] [<username>] [<hostname>] [<mailbox>]
> 
> >

**Comment by dgossage** [comment] 2019-03-07 21:26
Even sending from mail via cli and I see Content-Type set it is failing 

User-Agent: Heirloom mailx 12.4 7/29/08
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

**Comment by glensc** [comment] 2019-03-07 21:27
I think this got fixed in 3.6.0: #452

if it did not, please provide raw email that causes the error. attach as upload for example

there's another fix in 3.6.1: #477

**Comment by glensc** [comment] 2019-03-07 21:28
and please use markdown code-fence for formatting such texts:

    ```
    some text
    ```

**Comment by dgossage** [comment] 2019-03-07 21:32
Sorry thought I clicked that but think I deleted content then forgot to re-add it.

I'll see if I can update tonight or over weekend to 3.6 line
for moment I had to revert code back to 3.5.4 from yesterday so people could get tickets to work on

**Comment by glensc** [comment] 2019-03-07 21:35
please note that 3.6 requires 7.1 php runtime!

**Comment by glensc** [comment] 2019-03-07 21:36
you can probably cherry-pick the changes from mentioned PRs, as long the changes don't require php 7.1.

**Comment by dgossage** [comment] 2019-03-07 22:08
I can jump straight from 3.5.6 to 3.6.1 or do I need to run upgrade with 3.6.0 first?

**Comment by dgossage** [comment] 2019-03-08 06:45
Unfortunately after update to php71 and 3.6.1 I just got mysql login issues  and it got late so just reimported old database and rolled back to 3.5.4 again.

`[08-Mar-2019 06:09:30 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getOne() on boolean in /www/sites/www.checktix.com/public/lib/eventum/class.user.php:461
Stack trace:
#0 /www/sites/www.checktix.com/public/lib/eventum/auth/AuthCookie.php(89): User::getUserIDByEmail('dgossage@carous...')
#1 /www/sites/www.checktix.com/public/lib/eventum/auth/AuthCookie.php(59): AuthCookie::hasAuthCookie()
#2 /www/sites/www.checktix.com/public/lib/eventum/class.auth.php(314): AuthCookie::getAuthCookie()
#3 /www/sites/www.checktix.com/public/src/Monolog/AppInfoProcessor.php(32): Auth::getUserID()
#4 [internal function]: Eventum\Monolog\AppInfoProcessor->__invoke(Array)
#5 /www/sites/www.checktix.com/public/vendor/monolog/monolog/src/Monolog/Logger.php(340): call_user_func(Object(Eventum\Monolog\AppInfoProcessor), Array)
#6 /www/sites/www.checktix.com/public/vendor/monolog/monolog/src/Monolog/Logger.php(609): Monolog\Logger->addRecord(400, 'Uncaught Except...', Array)
#7 /www/sites/www.checktix.com/public/vendor/monolog/monolog/src/Monolog/ErrorHandler. in /www/sites/www.checktix.com/public/lib/eventum/class.user.php on line 461
`

**Comment by glensc** [comment] 2019-03-08 08:55
you can skip 3.6.0 if you update 3.5.6 to 3.6.1

**Comment by glensc** [comment] 2019-03-08 08:58
looks like you got `false` from `getInstance` method, but I do not see how.

https://github.com/eventum/eventum/blob/v3.6.1/lib/eventum/class.db_helper.php#L28-L66

**Comment by dgossage** [comment] 2019-03-08 12:36
I'll test again over weekend if I can when I have a little more time.  It was getting to end of a long day and I may have just had something configured wrong I wasn't seeing.

**Comment by glensc** [comment] 2019-03-08 13:05
as you probably figured yourself, the failure is caused by fault in the database connection. likely nothing to do with Eventum code changes.

however, when I read the code myself, I can not understand how that method can return `false` :)

**Comment by dgossage** [comment] 2019-03-08 13:13
Is their an example output of the config files that upgrade script should
leave me with? php71 seemed to load eventum 3.5.x so wondering if for some
reason my config.php or setup.php has something weird in it i wasn't
noticing

*David Gossage*
*Carousel Checks Inc. | System Administrator*
*Office* 708.613.2284

**Comment by glensc** [comment] 2019-03-08 14:58
3.5.x likely works with php 7.1, it emits notices here and there.

this one i know is needed:
- d819dbc8e

3.5.6->3.6.0 adds these migrations:

```
$ git diff --stat v3.5.6..v3.6.0 db/
 db/migrations/20190115211455_eventum_auth_adapter_setup.php        |  90 +++++++++++++++
 db/migrations/20190123140920_eventum_remote_links.php              |  30 +++++
 db/migrations/20190127204900_eventum_login_back_off_config.php     |  61 ++++++++++
 db/migrations/20190208111102_eventum_remote_links_date.php         |  25 +++++
 db/migrations/20190211142511_eventum_remote_link_create_date.php   |  26 +++++
```

of these modify `config/setup.php`:
- [20190115211455_eventum_auth_adapter_setup](https://github.com/eventum/eventum/blob/v3.6.0/db/migrations/20190115211455_eventum_auth_adapter_setup.php)
- [20190127204900_eventum_login_back_off_config](https://github.com/eventum/eventum/blob/v3.6.0/db/migrations/20190127204900_eventum_login_back_off_config.php)

**Closed** 2019-05-01 07:56 UTC
Labels: question

**Comment by dgossage** [comment] 2019-05-29 16:19
Just wanted to share for posterity if anyone else updates from a much older version that I narrowed down the issue to the setup.php database section not having correct entries after running upgrade.

Old version had me with this in database section
```
'database'` => 
  array (
    'driver' => 'mysql',
    'hostname' => 'localhost',
    'database' => 'test',
    'username' => 'testu',
    'password' => 'testp',
    'port' => 3306,
    'table_prefix' => '',
    'classname' => 'Pear',
  `),
```

Compared it with a fresh install which removes driver, table_prefix and added socket and charset.  I imagine it was actually the driver portion.
new section that worked was 
```
'database' => [
        'hostname' => 'localhost',
        'database' => 'test',
        'username' => 'testu',
        'password' => 'testp',
        'port' => 3306,
        'charset' => 'utf8',
        'socket' => null,
    ],

```
