### ISSUE TITLE
Getting error 'Sorry, the page you are looking for could not be found.'

### ISSUE THREAD

**Issue by GaneshKandu** [eventum/eventum#565] opened 2019-05-23 05:46 UTC
**Version(s) affected**: 3.7.1

**Description**  
Getting error 'Sorry, the page you are looking for could not be found.'
on login page after successful installation

**How to reproduce**  
install 3.7.1 after installing visit http://domain.com/eventum371/htdocs/

**Additional context**  
![webuzo2 web manual eventum371 htdocs -1](https://user-images.githubusercontent.com/12833130/58228369-1718d280-7d4c-11e9-961d-f73ba97b4507.png)

**Comment by glensc** [comment] 2019-05-23 09:49
this seems specific to your webserver and webserver configuration. likely the rewrite rules are unexpected. sharing these details might help others to reproduce.

also, you should not expose anything outside `htdocs` to webserver:
- https://github.com/eventum/eventum/wiki/System-Admin%3A-Doing-a-fresh-install

**Comment by basepr1me** [comment] 2019-05-24 20:20
Ganesh, I have the same error. I was able to bypass by adding index.php to the URL, until I can suss out the problem. (added patch to index.php to look for document_uri and rewrite header if file not there). Since I don't do apache, .htaccess isn't honored.

**Comment by glensc** [comment] 2019-05-25 11:23
can you share patches?

**Comment by basepr1me** [comment] 2019-05-26 02:43
On May 25, 2019 5:23:31 AM MDT, "Elan Ruusamäe" <notifications@github.com> wrote:
>can you share patches?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/eventum/eventum/issues/565#issuecomment-495909973

I can when I get back to work. However, it's not the right way to do anything and VERY hackish. I don't like it.
-- 
Tracey Emery

**Comment by glensc** [comment] 2019-05-26 07:14
I don't understand why is your setup different than mine that it's broken. seeing your patch might help to understand.

**Comment by basepr1me** [comment] 2019-05-26 15:41
On May 26, 2019 1:14:47 AM MDT, "Elan Ruusamäe" <notifications@github.com> wrote:
>I don't understand why is your setup different than mine that it's
>broken. seeing your patch might help to understand.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/eventum/eventum/issues/565#issuecomment-495975799

I'm away from work and won't have access until Tuesday. The patch is a hackish redirect and NOT the right way to do it. It is just a stopgap measure to get me by until I figure out the problem.
-- 
Tracey Emery

**Comment by glensc** [comment] 2019-05-26 16:58
any of you actually describe your setup, to reproduce?

**Comment by GaneshKandu** [comment] 2019-05-28 05:34
@glensc i think its redirection issue
i have installed in sub-folder of webroot
ex.
http://domain.com/subfolder/htdocs

**Comment by glensc** [comment] 2019-05-28 10:12
so accessing with a trailing slash is fine?
- http://domain.com/subfolder/htdocs/

**Comment by glensc** [comment] 2019-05-28 10:13
... and still no description of the setup. sigh...

**Comment by GaneshKandu** [comment] 2019-05-28 11:56
> so accessing with a trailing slash is fine?
> 
>     * http://domain.com/subfolder/htdocs/

Not Working

**Comment by GaneshKandu** [comment] 2019-05-28 12:05
> 
> 
> so accessing with a trailing slash is fine?
> 
>     * http://domain.com/subfolder/htdocs/

adding index.php works
http://domain.com/subfolder/htdocs/index.php

**Comment by basepr1me** [comment] 2019-05-28 14:07
On Tue, May 28, 2019 at 12:06:10PM +0000, Ganesh Kandu wrote:
> > 
> > 
> > so accessing with a trailing slash is fine?
> > 
> >     * http://domain.com/subfolder/htdocs/
> 
> adding index.php works
> http://domain.com/subfolder/htdocs/index.php
>  
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/eventum/eventum/issues/565#issuecomment-496488488

Current setup for me is OpenBSD running httpd. Patch to make work
attached. Again, this patch is just a hack until I can figure out why,
as of 3.7.0, a trailing slash alone won't work.

In this patch, the /support/ path is a symlink to ../eventum/htdocs, which
resides one level up from the root directory. This has worked flawlessly
up until the 3.7.0 switch.

--- eventum/htdocs/index.php.orig	Fri May 24 13:55:20 2019
+++ eventum/htdocs/index.php	Fri May 24 13:52:01 2019
@@ -11,6 +11,11 @@
  * that were distributed with this source code.
  */
 
+if ($_SERVER['REQUEST_URI'] != $_SERVER['DOCUMENT_URI']) {
+	header("Location: https://www.xxxxxx.us/support/index.php");
+	exit();
+}
+
 use Eventum\Kernel;
 
 require __DIR__ . '/../init.php';

**Comment by glensc** [comment] 2019-05-28 15:15
well, obviously the breakage is due Symfony routing being used for index.php, noted in changelog: https://github.com/eventum/eventum/blob/v3.7.0/CHANGELOG.md

**Comment by basepr1me** [comment] 2019-05-28 15:44
Ok, thanks. Adding the following to config/routes.yml fixed the issue:

support:                                                                                                                                                                                                       
     path: /support                                                                                                                                                                                             
     controller: Eventum\Controller\IndexController::defaultAction

**Comment by glensc** [comment] 2019-06-02 16:45
perhaps it also helps to add:

```yml
index2:
    path: /index.php
    controller: Eventum\Controller\IndexController::defaultAction
```

**Comment by GaneshKandu** [comment] 2019-06-03 05:57
> 
> 
> perhaps it also helps to add:
> 
> ```yaml
> index2:
>     path: /index.php
>     controller: Eventum\Controller\IndexController::defaultAction
> ```

Not Working for me

**Comment by basepr1me** [comment] 2019-06-04 13:56
Well, based on what you've posted, seems you have the eventum folder available to the public, so you'd need to do a two-level route, perhaps?

http://domain.com/subfolder/htdocs/index.php would be:

```
title:
    path: /subfolder/htdocs
    controller: Eventum\Controller\IndexController::defaultAction
```
Also, the public should never have access to http://domain.com/subfolder. Just thinking based on what you've posted.

**Comment by GaneshKandu** [comment] 2019-07-08 12:06
Hi,
Getting same issue in Eventum 3.7.2

**Comment by glensc** [comment] 2019-07-08 15:12
And the issue is still open.

however, not this guarantees fix, but you have not given you setup description as I asked: https://github.com/eventum/eventum/issues/565#issuecomment-495149138

asked repeatedly: https://github.com/eventum/eventum/issues/565#issuecomment-496015442

**Comment by GaneshKandu** [comment] 2019-07-11 08:28
setup description:

O.S - CentOS release 6.4 (Final)
PHP version - 7.1.26
MYSQL version - 5.5.54
Webserver type and version - Apache/2.2.34

**Comment by prbt2016** [comment] 2019-07-18 04:44
@glensc  Even i face the same above error mentioned above after a successful install on this environment PHP 7.1 and MySQL 5.6, Apache 2.2.

**Comment by prbt2016** [comment] 2019-08-06 05:00
@glensc Just wanted to know how to make the script work on shared hosting?. As per your documentation here:
https://github.com/eventum/eventum/wiki/System-Admin%3A-Doing-a-fresh-install

PLEASE NOTE: The whole eventum directory should NOT be accessible under the webserver, only /path-to-eventum/htdocs/

So if this is the case, then it would require a virtual host setup which isn't allowed on many shared hosts to edit the apache conf file. Is there any other way to configure the script ? As there is no clear documentation regarding this. Would you please update the documentation on this or give a resolution on this?

**Comment by glensc** [comment] 2020-08-20 13:04
similar issue: https://github.com/eventum/eventum/issues/634

closing this as duplicate

**Closed by glensc** 2020-08-20 13:04 UTC
Labels: question
