### ISSUE TITLE
Issue closed comments aren't sent

### ISSUE THREAD

**Issue by phavel** [eventum/eventum#268] opened 2017-05-19 08:35 UTC
I noticed Eventum not sending e-mail with note of close "Note: Issue closed comments" after close issue. This problem occurred when I upgrade version from 3.0.11 to 3.1.05. 
Close comment is not instert into buffer table "mail_queue". No error show during closing issue. 

Do you have same problem or problem is only with me?

**Comment by phavel** [comment] 2017-05-19 09:25
Test: When I return change in commit 91e9ee6, problem is resolved.

**Comment by balsdorf** [comment] 2017-05-19 13:13
What settings do you select when you close for:

- "Send Notification About Issue Being Closed?"
- "Send Notification Reason To"

Are people listed next to "Internal Users" / "All Users"?

**Comment by phavel** [comment] 2017-05-19 15:20
- "Send Notification About Issue Being Closed?" → Yes
- "Send Notification Reason To" → Internal Users
- Are people listed next to "Internal Users"? → Yes, they are

**Comment by balsdorf** [comment] 2017-05-19 16:21
Are there multiple people on internal users or just the person closing the issue?

Do you have a workflow backend or customer backend setup?

**Comment by phavel** [comment] 2017-05-19 16:30
There are multiple people on internal users (note isn't send to person closing the issue → it is correct).

I have no  workflow backend or customer backend setup (folders crm, custom_field, include, partner, templates and workflow in config folder are empty).

**Comment by balsdorf** [comment] 2017-05-19 17:20
Odd. I can't reproduce this.

Unfortunately I think you will have to start adding debugging to see what is going on. 

I'd start by making sure this $send_notification == 1 here: https://github.com/eventum/eventum/blob/4c842a0fbb4cd82d24e3f7724bd1a59caa9b51ef/lib/eventum/class.issue.php#L1323

And then see what values are passed to https://github.com/eventum/eventum/blob/4c842a0fbb4cd82d24e3f7724bd1a59caa9b51ef/lib/eventum/class.notification.php#L832

**Comment by phavel** [comment] 2017-05-21 21:00
Output:

```
send_notification: 1 

issue_id: 73 
type: closed
entry_id:
internal_only: 1 
extra_recipients: 
```


However, I think there will be problem in adding/sending a note in calling function [insertNote](https://github.com/eventum/eventum/blob/4c842a0fbb4cd82d24e3f7724bd1a59caa9b51ef/lib/eventum/class.issue.php#L1319), because e-mail with issue close is send OK. Only isn't sent e-mail with note for close.

**Comment by balsdorf** [comment] 2017-05-22 17:49
My fix in  91e9ee6 prevents insertNote from sending a note because we want it included in the close issue notice, not a separate notes.

Add debug for $users [here](https://github.com/eventum/eventum/blob/4c842a0fbb4cd82d24e3f7724bd1a59caa9b51ef/lib/eventum/class.notification.php#L845) both when closing an issue and when sending a note.

I'm also wondering if [this](https://github.com/eventum/eventum/blob/4c842a0fbb4cd82d24e3f7724bd1a59caa9b51ef/lib/eventum/class.notification.php#L865) check is failing.

**Comment by phavel** [comment] 2017-05-23 11:01
Output:

When send note:
```
$users: Array
(
    [0] => Array
        (
            [sub_usr_id] => 5
            [sub_email] => 
        )
    [1] => Array
        (
            [sub_usr_id] => 8
            [sub_email] => 
        )
)
$internal_only: 1
User::getRoleByUser(…): 4
User::ROLE_USER: 4
```

When issue close:
```
$users: Array
(
    [0] => Array
        (
            [sub_usr_id] => 5
            [sub_email] => 
            [pru_role] => 7
        )
    [1] => Array
        (
            [sub_usr_id] => 8
            [sub_email] => 
            [pru_role] => 4
        )
)
$internal_only: 1
User::getRoleByUser(…): 4
User::ROLE_USER: 4
```

**Comment by balsdorf** [comment] 2017-05-24 17:35
Debug what is passed [here](https://github.com/eventum/eventum/blob/4c842a0fbb4cd82d24e3f7724bd1a59caa9b51ef/lib/eventum/class.notification.php#L992) as well

**Comment by glensc** [comment] 2017-09-20 20:11
@phavel, @balsdorf  can this be closed?

**Comment by phavel** [comment] 2017-09-20 20:16
I am sorry, in last months I did not have time to test. (Problem is not solved.)

**Comment by glensc** [comment] 2021-05-18 19:52
The 91e9ee6712 commit was reverted in a30f8d04f via #631, so this is now solved.

**Closed by glensc** 2021-05-18 19:52 UTC
Labels: bug
